on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - b-dockerdeploy
  pull_request:
    branches:
      - main
      - master

jobs:
  test-compose-action:
    runs-on: ubuntu-latest
    name: Zig build
    strategy:
      fail-fast: false
      matrix:
        zigver: 
        - '0.9.0'
        - '0.9.1'
        - '0.10.0'
        - '0.10.1'
        - '0.11.0-dev.4003+c6aa29b6f'
    steps:
      - uses: actions/checkout@v3
      - name: Docker Compose multi-stage build
        run: docker-compose -f docker-compose.yml.sample build --build-arg "ZIGVER=${{ matrix.zigver }}"